apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud
data:
  TZ: Europe/Paris
  DEBUG: "false"
  NEXTCLOUD_URL: https://nextcloud-nextcloud.apps.kpouget-20220309.psap.aws.rhperfscale.org
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_TRUSTED_DOMAINS: nextcloud-nextcloud.apps.kpouget-20220309.psap.aws.rhperfscale.org
  NEXTCLOUD_UPLOAD_MAX_FILESIZE: 4G
  NEXTCLOUD_MAX_FILE_UPLOADS: "200"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db
data:
  MYSQL_DATABASE: nextcloud
  MYSQL_HOST: nextcloud-pod-0:3306
  MYSQL_USER: nextcloud
