apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud
  namespace: nextcloud
data:
  TZ: Europe/Paris
  DEBUG: "false"
  NEXTCLOUD_URL: https://cloud.groupe-speleo-quercy.fr
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_TRUSTED_DOMAINS: cloud.groupe-speleo-quercy.fr
  NEXTCLOUD_UPLOAD_MAX_FILESIZE: 4G
  NEXTCLOUD_MAX_FILE_UPLOADS: "200"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db
  namespace: nextcloud
data:
  MYSQL_DATABASE: nextcloud
  MYSQL_HOST: db.nextcloud.svc:3306 
  MYSQL_USER: nextcloud
