---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/data/nextcloud/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: nextcloud-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-html
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/data/nextcloud/html"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html
  namespace: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nextcloud-html
