---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/data/nextcloud/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nextcloud-db
