---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: website-db
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/data/website/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: website-bolt
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: website-db
