apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nc
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nc
  template:
    metadata:
      labels:
        app: nc
    spec:
      containers:
      - name: nc
        securityContext:
          privileged: true
        env:
        - name: TZ
          value: Europe/Paris
        - name: DEBUG
          value: "false"
        - name: NEXTCLOUD_URL
          value: https://cloud.groupe-speleo-quercy.fr
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "cloud.groupe-speleo-quercy.fr"
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nc
              key: NEXTCLOUD_ADMIN_PASSWORD
        - name: NEXTCLOUD_UPLOAD_MAX_FILESIZE
          value: 4G
        - name: NEXTCLOUD_MAX_FILE_UPLOADS
          value: "200"

        - name: MYSQL_DATABASE
          value: nextcloud

        - name: MYSQL_HOST
          value: nextcloud-db.nextcloud.svc:3306
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: MYSQL_PASSWORD
        - name: MYSQL_USER
          value: nextcloud
        image: docker.io/library/nextcloud@sha256:5b97169f2f986237472b0a0da84bab98b199cc36439e29f9a9b56d17343b50b4
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/html
          name: html
        - mountPath: /var/www/html/data
          name: data
      restartPolicy: Always
      volumes:
        - name: data
          hostPath:
            path: "/data/nextcloud/data"
            type: DirectoryOrCreate
        - name: html
          hostPath:
            path: "/data/nextcloud/html"
            type: DirectoryOrCreate
