security:
    encoders:
        Bolt\Entity\User: auto
    providers:
        database_users:
            entity: { class: Bolt\Entity\User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: Bolt\Security\UserChecker
            logout: { path: bolt_logout, target: bolt_login }
            remember_me: { secret: '%kernel.secret%', lifetime: 2592000, remember_me_parameter: 'login[remember_me]' }
            custom_authenticators: [Bolt\Security\LoginFormAuthenticator]
            entry_point: Bolt\Security\AuthenticationEntryPointRedirector
        api:
            pattern: ^/api
            http_basic: ~
    role_hierarchy:
        ROLE_DEVELOPER:
            - ROLE_ADMIN
            - ROLE_CAN_SWITCH_USER
        ROLE_ADMIN:
            - ROLE_CHIEF_EDITOR
        ROLE_CHIEF_EDITOR:
            - ROLE_EDITOR
        ROLE_EDITOR:
            - ROLE_USER
        ROLE_USER: {  }
        ROLE_WEBSERVICE: {  }
    access_control:
        -
            path: ^%bolt.backend_url%/login$
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^%bolt.backend_url%/reset-password
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^%bolt.backend_url%/api
            roles: ADMIN_API_ACCESS
        -
            path: ^/(%app_locales%)%bolt.backend_url%/api
            roles: ADMIN_API_ACCESS
        -
            path: ^%bolt.backend_url%/_trans
            roles: ADMIN_TRANSLATE_ACCESS
        -
            path: ^/(%app_locales%)%bolt.backend_url%/_trans
            roles: ADMIN_TRANSLATE_ACCESS
        -
            path: ^%bolt.backend_url%
            roles: IS_AUTHENTICATED_REMEMBERED
        -
            path: ^/(%app_locales%)%bolt.backend_url%
            roles: IS_AUTHENTICATED_REMEMBERED
    enable_authenticator_manager: true
    password_hashers:
        Bolt\Entity\User: auto
